/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    'Ырщз': typeof import('./src/components/Ырщз.vue')['default']
    BottomMenu: typeof import('./src/components/basic/BottomMenu.vue')['default']
    Dialog: typeof import('./src/components/Dialog.vue')['default']
    ErrorNotify: typeof import('./src/components/basic/ErrorNotify.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    InventoryItem: typeof import('./src/components/InventoryItem.vue')['default']
    MainLoading: typeof import('./src/components/basic/MainLoading.vue')['default']
    MineLoader: typeof import('./src/components/MineLoader.vue')['default']
    MissionItem: typeof import('./src/components/MissionItem.vue')['default']
    MIssionItem: typeof import('./src/components/MIssionItem.vue')['default']
    Navbar: typeof import('./src/components/basic/Navbar.vue')['default']
    PageLoading: typeof import('./src/components/basic/PageLoading.vue')['default']
    PageSoon: typeof import('./src/components/basic/PageSoon.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Shop: typeof import('./src/components/Shop.vue')['default']
    ShopView: typeof import('./src/components/ShopView.vue')['default']
    StatsInfo: typeof import('./src/components/StatsInfo.vue')['default']
    Timer: typeof import('./src/components/Timer.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanCell: typeof import('vant/es')['Cell']
    VanDialog: typeof import('vant/es')['Dialog']
    VanGrid: typeof import('vant/es')['Grid']
    VanGridItem: typeof import('vant/es')['GridItem']
    VanIcon: typeof import('vant/es')['Icon']
    VanImage: typeof import('vant/es')['Image']
    VanLoading: typeof import('vant/es')['Loading']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanProgress: typeof import('vant/es')['Progress']
    VanRow: typeof import('vant/es')['Row']
    VanSpace: typeof import('vant/es')['Space']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
  }
}
