/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    'Ырщз': typeof import('./src/components/Ырщз.vue')['default']
    BottomMenu: typeof import('./src/components/BottomMenu.vue')['default']
    Dialog: typeof import('./src/components/Dialog.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    MineLoader: typeof import('./src/components/MineLoader.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Shop: typeof import('./src/components/Shop.vue')['default']
    ShopView: typeof import('./src/components/ShopView.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanDialog: typeof import('vant/es')['Dialog']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanProgress: typeof import('vant/es')['Progress']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
  }
}
